# Generated by Django 6.0.6 on 2026-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(choices=[('Sarapan', 'Sarapan'), ('Makan Siang', 'Makan Siang'), ('Makan Malam', 'Makan Malam'), ('Cemilan', 'Cemilan')], max_length=20)),
                ('menu', models.CharField(max_length=200)),
                ('kalori', models.IntegerField(help_text='Estimasi kalori')),
            ],
        ),
    ]
