# Generated by Django 6.0.6 on 2026-06-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(choices=[('Sarapan', 'Sarapan'), ('Makan Siang', 'Makan Siang'), ('Makan Malam', 'Makan Malam'), ('Cemilan', 'Cemilan')], max_length=20)),
                ('menu', models.CharField(max_length=200)),
                ('kalori', models.IntegerField(help_text='Estimasi kalori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_makan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
